# Generated by Django 4.2 on 2025-02-28 07:54

from django.db import migrations, models
import movie_web_uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('movie', models.FileField(upload_to='movie/%Y/%m/', validators=[movie_web_uploads.models.validate_extension_movie])),
                ('image', models.FileField(upload_to='movieimage/%Y/%m/', validators=[movie_web_uploads.models.validate_extension_image])),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
